- name: install packages
  package:
    name:
      - acl
      - attr
      - dnsutils
      - krb5-user
      - krb5-config
      - libpam-winbind
      - libnss-winbind
      - samba
      - samba-common
      - samba-dsdb-modules
      - samba-vfs-modules
      - winbind
    state: present