- name: Creates directory /srv/samba/printer_drivers
  file:
    path: /srv/samba/printer_drivers
    state: directory
    owner: root
    group: "{{ printer_server_realm }}\\Domain Admins"
    mode: '2775'
    recurse: yes
